- name: Download wordpress
  get_url:
    url: "{{ url }}"
    dest: "{{ tar_file }}"

- name: Extract file
  unarchive:
    src: "{{ tar_file }}"
    dest: /tmp
    remote_src: yes

- name: copy files and chown
  copy:
    src: /tmp/wordpress/.
    dest: /var/www/html/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '755'
    remote_src: yes

- name: Template a file to html folder
  template:
    src: roles/wordpress/templates/wp-config-sample.php.j2
    dest: /var/www/html/wp-config.php