- name: Install the latest version of Apache
  ansible.builtin.yum:
    name: "{{ apache }}"
    state: latest

- name: Start service apache
  ansible.builtin.service:
    name: "{{ apache }}"
    state: started
    enabled: yes

- name: Restart Apache
  ansible.builtin.service:
    name: "{{ apache }}"
    state: restarted