- hosts: all
  become: true
  tasks:
    - name: remirepo PHP-7.4
      yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present

    - name: enable remirepo
      yum_repository:
        name: remi-php74
        description: remirepo
        baseurl: https://rpms.remirepo.net/enterprise/7/php74/x86_64/
        gpgcheck: yes
        gpgkey: https://rpms.remirepo.net/RPM-GPG-KEY-remi
        enabled: yes

    - name: install packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
          - httpd
          - wget
          - unzip
          - epel-release
          - mysql
          - mariadb
          - mariadb-server
          - php
          - php-mysqli

    - name: install wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/latest.tar.gz

    - name: unzip wordpress
      unarchive:
        src: /tmp/latest.tar.gz
        dest: /var/www/html/
        remote_src: yes
      notify:
        - restart apache

    - name: move files out of folder
      shell: mv /var/www/html/wordpress/* /var/www/html/

    - name: chown
      file:
        path: /var/www/html/
        owner: apache
        group: apache
        recurse: yes

    - name: start apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Start and enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes
  


  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
