
- name: Start mariadb
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Create a new database with name '"{{ db_name }}"'
  community.mysql.mysql_db:
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    name: "{{ db_name }}"
    state: present

- name: Create database user with name 'zak' and password '123' with all database privileges
  community.mysql.mysql_user:
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    name: zak
    password: 123
    priv: '*.*:ALL'
    state: present
    column_case_sensitive: false
